language: node_js

node_js:
    - "5.11"

cache:
    directories:
        - elm-client/tests/elm-stuff/build-artifacts

install:
    - npm install -g elm@0.17 elm-test@0.17
    - npm install

env:
  - CXX=g++-4.8 DATABASE_URL="postgres://postgres:@localhost:5432/travis_ci_test" JWT_SECRET=jwtsecret

addons:
    postgresql: "9.4"
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

services:
    - postgresql

before_script:
    - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
    - npm run setup

script:
    - npm test
