web:
  build: .
  command: nodemon --harmony server.js
  working_dir: /var/www
  volumes:
    - .:/var/www/
  links:
   - postgres
  ports:
   - "3000:3000"
  env_file:
    - ./envvars

postgres:
    image: postgres:9.4
