web:
  image: kimlai/music-feed
  command: nodemon --harmony server.js
  working_dir: /var/www
  links:
   - postgres
  ports:
   - "3000:3000"
  env_file:
    - ./envvars
  environment:
    DATABASE_URL: postgres://postgres:@postgres:5432/postgres

postgres:
    image: postgres:9.4
